os: linux
dist: xenial
language: node_js
node_js: lts/*

script:
  - npm run quality:check
  - npm run build
  - npm test

deploy:
  - provider: npm
    on:
      branch: main
      tags: true
      repo: tylergrinn/tygr-auth-server
    edge: true
    email: tylergrinn@gmail.com
    api_token: $NPM_TOKEN
